// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDU8JQc3dk-Z0_0-UtWZ9URpjnMQfF4STk',
    appId: '1:1010857677111:web:05e296cd2bbaf135140ab2',
    messagingSenderId: '1010857677111',
    projectId: 'rovemaillogin',
    authDomain: 'rovemaillogin.firebaseapp.com',
    databaseURL: 'https://rovemaillogin-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rovemaillogin.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdiVMYkCPK9zaloTkQ2q9IS2xthmzJFZ4',
    appId: '1:1010857677111:android:9ce0c8a330d9a833140ab2',
    messagingSenderId: '1010857677111',
    projectId: 'rovemaillogin',
    databaseURL: 'https://rovemaillogin-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rovemaillogin.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMw0oA2mCdXr_EYMW__cTcMaZgjcqOqaQ',
    appId: '1:1010857677111:ios:b3c76dd5a9ddb8f8140ab2',
    messagingSenderId: '1010857677111',
    projectId: 'rovemaillogin',
    databaseURL: 'https://rovemaillogin-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rovemaillogin.appspot.com',
    iosBundleId: 'com.example.roveApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMw0oA2mCdXr_EYMW__cTcMaZgjcqOqaQ',
    appId: '1:1010857677111:ios:36a4cfaf43fd767e140ab2',
    messagingSenderId: '1010857677111',
    projectId: 'rovemaillogin',
    databaseURL: 'https://rovemaillogin-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rovemaillogin.appspot.com',
    iosBundleId: 'com.example.roveApp.RunnerTests',
  );
}
